---
abstract: 'Add your dist to a Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Pinto-Add
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::Plugin::Pinto::Add:
    file: lib/Dist/Zilla/Plugin/Pinto/Add.pm
    version: 0.028
requires:
  Class::Load: 0
  Dist::Zilla::Role::Releaser: 0
  English: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Moose: 0
  Pinto::Types: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/thaljef/Dist-Zilla-Plugin-Pinto-Add/issues
  repository: git://github.com/thaljef/Dist-Zilla-Plugin-Pinto-Add.git
version: 0.028
