---
abstract: 'Ship your dist to a Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@stratopan.com>'
build_requires:
  Dist::Zilla::Tester: 0
  ExtUtils::MakeMaker: 0
  File::Path: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::Which: 0
  List::Util: 0
  Module::Build: 0.4005
  Test::DZil: 0
  Test::Exception: 0
  Test::More: 0.96
  strict: 0
  warnings: 0
configure_requires:
  File::Which: 0
  Module::Build: 0.4005
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Pinto-Add
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::Plugin::Pinto::Add:
    file: lib/Dist/Zilla/Plugin/Pinto/Add.pm
    version: 0.088
requires:
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::Releaser: 0
  File::Which: 0
  IPC::Run: 0
  Moose: 0
  MooseX::Types::Moose: 0
  perl: 5.006
  version: 0
resources:
  bugtracker: https://github.com/thaljef/Dist-Zilla-Plugin-Pinto-Add/issues
  homepage: https://metacpan.org/module/Dist-Zilla-Plugin-Pinto-Add
  repository: git://github.com/thaljef/Dist-Zilla-Plugin-Pinto-Add.git
version: 0.088
